# Generated by Django 3.0.4 on 2020-04-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=25)),
                ('nombre_contacto', models.CharField(max_length=25)),
                ('apellido1_contacto', models.CharField(max_length=25)),
                ('apellido2_contacto', models.CharField(max_length=25)),
                ('telf_cliente', models.IntegerField()),
                ('email_cliente', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido1', models.CharField(max_length=25)),
                ('apellido2', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_tarea', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('nota_adicional', models.TextField(max_length=750)),
                ('estadoTarea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appDeustotilTECHSL.EstadoTarea')),
                ('prioridad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appDeustotilTECHSL.Prioridad')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDeustotilTECHSL.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('presupuesto', models.FloatField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appDeustotilTECHSL.Cliente')),
                ('empleados', models.ManyToManyField(to='appDeustotilTECHSL.Empleado')),
                ('tareas_a_realizar', models.ManyToManyField(to='appDeustotilTECHSL.Tarea')),
            ],
        ),
    ]
