# Generated by Django 3.0.4 on 2020-04-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotilTECHSL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDeustotilTECHSL.Cliente'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estadoTarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDeustotilTECHSL.EstadoTarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDeustotilTECHSL.Prioridad'),
        ),
    ]
