# Generated by Django 3.0.4 on 2020-04-16 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotilTECHSL', '0002_auto_20200411_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto_perfil',
            field=models.ImageField(default='fotos_perfil/no-img.jpg', upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2020, 4, 16)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2020, 4, 16)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estadoTarea',
            field=models.ForeignKey(default='Abierta', on_delete=django.db.models.deletion.CASCADE, to='appDeustotilTECHSL.EstadoTarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2020, 4, 16)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2020, 4, 16)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='nota_adicional',
            field=models.TextField(default='Rellena este campo con información adicional', max_length=750),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.ForeignKey(default='Ninguna', on_delete=django.db.models.deletion.CASCADE, to='appDeustotilTECHSL.Prioridad'),
        ),
    ]
