# Generated by Django 3.0.4 on 2020-04-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotilTECHSL', '0006_auto_20200416_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appDeustotilTECHSL.Cliente'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estadoTarea',
            field=models.ForeignKey(default='Abierta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appDeustotilTECHSL.EstadoTarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.ForeignKey(default='Ninguna', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appDeustotilTECHSL.Prioridad'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appDeustotilTECHSL.Empleado'),
        ),
    ]
