# Generated by Django 3.0.4 on 2020-04-21 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotilTECHSL', '0007_auto_20200416_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='tareas_a_realizar',
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appDeustotilTECHSL.Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2020, 4, 21)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2020, 4, 21)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2020, 4, 21)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2020, 4, 21)),
        ),
    ]
