# Generated by Django 3.0.4 on 2020-04-21 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotilTECHSL', '0009_auto_20200421_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 8, 37, 13, 23381, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 8, 37, 13, 23381, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 8, 37, 13, 27760, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2020, 4, 21, 8, 37, 13, 27760, tzinfo=utc)),
        ),
    ]
