# Generated by Django 3.0.4 on 2020-04-21 11:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotilTECHSL', '0013_auto_20200421_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tareas_a_realizar',
            field=models.ManyToManyField(to='appDeustotilTECHSL.Tarea'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appDeustotilTECHSL.Cliente'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2020, 4, 21)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2020, 4, 21)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2020, 4, 21)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2020, 4, 21)),
        ),
    ]
