# Generated by Django 3.0.4 on 2020-05-18 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotilTECHSL', '0014_auto_20200421_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estadoTarea',
            field=models.CharField(default='Asignada', max_length=15),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2020, 5, 18)),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(default='Ninguna', max_length=15),
        ),
        migrations.DeleteModel(
            name='EstadoTarea',
        ),
        migrations.DeleteModel(
            name='Prioridad',
        ),
    ]
