# Generated by Django 3.0.4 on 2020-05-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotilTECHSL', '0015_auto_20200518_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_tarea', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estadoTarea',
            field=models.ForeignKey(default='Abierta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appDeustotilTECHSL.EstadoTarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.ForeignKey(default='Ninguna', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appDeustotilTECHSL.Prioridad'),
        ),
    ]
