# Generated by Django 3.0.4 on 2020-05-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDeustotilTECHSL', '0016_auto_20200518_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estadoTarea',
            field=models.CharField(default='Ninguna', max_length=25),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(default='Ninguna', max_length=25),
        ),
        migrations.DeleteModel(
            name='EstadoTarea',
        ),
        migrations.DeleteModel(
            name='Prioridad',
        ),
    ]
